export const fragments: string[] = [
	// On craft and code
	"the abstraction leaks, eventually",
	"somewhere between the spec and the ship",
	"the type system remembers",
	"elegance is the residue of constraint",
	"refactor the question",
	"debt, compounding",
	"the happy path is a lie",
	"naming things, still",
	"it compiled",
	"undefined is not a function",
	"off by one",
	"works on my machine",
	"TODO",
	"FIXME",
	"tech debt is just debt",
	"the tests pass",
	"the tests lie",
	"shipping",

	// On systems and complexity
	"the map is not the territory",
	"entropy wins",
	"layers all the way down",
	"the fallacies, distributed",
	"state is the enemy",
	"eventually consistent",
	"the network is not reliable",
	"latency is not zero",
	"there is no global clock",
	"configuration as code as configuration",
	"the monolith remembers",

	// Observational/philosophical
	"shipped",
	"not yet",
	"almost",
	"again",
	"the second system",
	"premature, as always",
	"good enough",
	"done is better than perfect",
	"perfect is the enemy of done",
	"simplify",
	"delete it",
	"rewrite",
	"the rewrite",
	"version 2",
	"legacy",
	"deprecated",
	"end of life",
	"maintenance mode",

	// Single words
	"async",
	"await",
	"null",
	"undefined",
	"void",
	"never",
	"unknown",
	"any",
];
