name: readme generator
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: generate README
        run: |-
          npm start --if-present
      - name: commit and push if changed
        run: |-
          git config --global user.email "jacksblan@gmail.com"
          git config --global user.name "Jackson Blankenship"
          git add -A
          git commit -m "chore(readme): regenerate readme" || exit 0
          git push
