name: Readme Generator
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Generate README
        run: |-
          npm start --if-present
      - name: Commit and push
        run: |-
          git config --global user.email "tars@flylance.com"
          git config --global user.name "TARS"
          git add -A
          git commit -m "chore(readme): regenerate readme" || exit 0
          git push
