name: shuffle

env:
  CI: true

on:
  push:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  shuffle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: |-
          yarn install --frozen-lockfile

      - name: Generate README
        run: |-
          yarn build
          yarn start

      - name: Commit and push
        run: |-
          git config --global user.email "tars@flylance.com"
          git config --global user.name "TARS"
          git add -A
          git commit -m "chore(readme): regenerate readme" || exit 0
          git push
